# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Portfolio.Repo.insert!(%Portfolio.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias Portfolio.Repo
alias Portfolio.Projects.Project

# add :name, :string
# add :class, :string
# add :semester, :string
# add :desc, :string
# add :imgs, {:array, :string}
# add :tags, {:array, :string}
# add :type, :integer
# ----> 1 graphic design, 2: coding, 3: UX/UI

# Graphic Type
# Date
# Time Spent
# Desc. 1 - n
# Tools Used
# Fun Rating

# project1 = Repo.insert!(%Project{class: "2D Fundamentals", type: 1, name: "Paint Collage", class_short: "2D", semester: "Fall '16", desc: "Final project 2D Fundamentals", imgs: ["2D/1_1_W.png"], tags: ["Art", "Acrylic Paint", "Illustrator"]});
# project2 = Repo.insert!(%Project{class: "3D Fundamentals", type: 1, name: "Shoe Storage Project", class_short: "3D", semester: "Spring '17", desc: "Final project 3D Fundamentals", imgs: ["3D/cover1.png", "3D/1_1_W.png", "3D/1_2_T.png", "3D/1_3_T.png", "3D/1_4_T.png", "3D/1_5_T.png"], tags: ["Design", "Sketch-Up"]});
# project3 = Repo.insert!(%Project{class: "3D Fundamentals", type: 1, name: "Hard-Drive Paper Model", class_short: "3D", semester: "Spring '17", desc: "3D Hard Drive sketch and paper model for 3D Fundamentals", imgs: ["3D/cover2.png", "3D/2_1_T.png"], tags: ["Sketch-Up"]});
# project4 = Repo.insert!(%Project{class: "Programming Basics", type: 2, name: "Planet Beat Looper", class_short: "PB", semester: "Fall '17", desc: "Final Project; Circular-based Beat Looper for Programming Baiscs", imgs: ["PB/1_1.png"], tags: ["P5.js"]});
project20 = Repo.insert!(%Project{class: "Personal", type: 3, name: "Yvette K. Teacher Website (WIP)", class_short: "Personal", semester: "Fall '21", desc: "(WIP) A free-lance project for a local high school art teacher, Yvette Kim. The website will be a showcase for her and her student's work, as well as being a 'sustainable' site for her to add and remove content directly on the website.", imgs: ["Freelance/1_1.png", "Freelance/1_0.png",  "I began my process by interviewing the teacher to understand her needs for the website. This included the target audience, wanted features, organization preferences, the site hierarchy and exactly what kind of content would be included.", "Freelance/1_1.png", "I was then able to take a sample of both her's and her student's work, to get a better feel for the artistic style of the teacher's content. From here, I went on to brainstorm and wireframe different site navigation layouts.", "Freelance/1_2.png", "Freelance/1_3.png", "Freelance/1_4.png", "Freelance/1_5.png", "Freelance/1_6.png", "After discussing these designs with the teacher and understanding which layouts she preferred and why, I designed several higher-fidelity mockups to give her a greater sense of what I would be creating for her.", "Freelance/1_7.png", "Freelance/1_8.png", "Freelance/1_9.png", "We eventually landed on this final design, which is currently being built out.", "Freelance/1_10.png"], tags: ["Figma", "Web Design", "Experience Design", "React.js"]});
project26 = Repo.insert!(%Project{class: "Group Design Capstone", type: 3, name: "PlayComb", class_short: "Capstone", semester: "Spring '21", desc: "Socialization is a crucial aspect of ones’ childhood, as it allows for minds to open up to creativity, emotions, and societal interactions, with the playground being a primary vessel for this kind of activity. My senior design capstone team designed PlayComb to provide an exciting, refreshing and practical playground experience for kids of all ages through a modular layout design focused on multiplicity and a ‘guiding-hand’ principle, all whist upholding social distancing. Our final deliverables included an example layout of a playground, 3D-printed scale models, an informative process book and website, as well as a demo of these playgrounds being walked through in AR.", imgs: ["Cap/cover.png", "Cap/0.png", "How has COVID affected play in children? This question moved our team to collect tons of research to understand the specific benefits of socialization at young ages, existing playground designs and their lack of use during the pandemic.", "Cap/1.png", "Understanding that play develops so many independenent and social skills, we began to tackle this problem with brainstorm sessions, sketching out various different play systems.", "Cap/2.png", "Cap/3.jpg", "At the same time, we spent time reseraching architects, kids, and parents, created storyboards based on their experiences, and outlined a project plan.", "Cap/4.png", "Cap/5.png", "We then landed on our modular-layout system, and began translating our sketches and ideas into 3D models in blender. This allowed us to break up into smaller teams to conduct AR testing, product testing, and develop visual design.", "Cap/6_0.png", "Cap/6.png", "Cap/6_AR.png", "Cap/7.png", "Cap/8.jpg", "After iterating and finalizing our designs in Blender, we created hyper-realistic renderings of our playground pieces, and created an example layout of our modular playgorund, PlayComb.", "Cap/9.png", "Cap/10.png"], tags: ["Web Design", "Blender", "Animation", "3D Print"]});
project18 = Repo.insert!(%Project{class: "Graphic Design 2", type: 1, name: "Data Privacy Campaign", class_short: "GD2", semester: "Fall '19", desc: "A Data Privacy Campaign is a project aimed at bringing awareness to data privacy, and the dangers surrounding it. After the first iteration of designs, which emphasized how much data is kept and given to large data corporations, I pivoted to a more “Big-Brother” inspired design-style, saying that social media corporations are always watching, always collecting data on user’s habits. The final deliverable was a website design mockup, series of Instagram Advertisements, series of posters, laptop and phone stickers, and business cards.", imgs: ["GD2/cover.png", "GD2/1_2.jpg", "GD2/1_3.jpg", "GD2/1_4.jpg", "GD2/1_10.jpg", "GD2/1_9.png", "GD2/1_6.png", "GD2/1_7.png", "GD2/1_8.png", "GD2/1_11.jpg", "GD2/1_12.jpg", "GD2/1_5.jpg"], tags: ["InDesign", "Illustrator", "Graphic Design"]});
project20 = Repo.insert!(%Project{class: "Interaction Design: Mobile", type: 3, name: "PhotoWalk", class_short: "ID:M", semester: "Fall '20", desc: "Photowalk is an app designed to encourage both digital and film photographers to become more familiar with their cities by going on “Photo Walks”, and expanding on their photography skills. By being able to share experiences through photos, walk routes, and specific stop locations, photographers can help others newer to the city to find interesting streets to take their own pictures of.", imgs: ["IDM/cover1.png", "IDM/0.png", "IDM/1_0.png", "Some early sketches and journey map.", "IDM/1_1.png", "IDM/1_2.png", "First set of prototypes.", "IDM/1_3.png", "Final Prototype.", "IDM/1_4.png", "IDM/1_5.png", "IDM/1_6.png"], tags: ["Figma", "Mobile Design", "Experience Design"]});
project23 = Repo.insert!(%Project{class: "Identity & Brand Design", type: 1, name: "Personal Identity Project", class_short: "I&BD", semester: "Spring '21", desc: "A series of three self-promotional posters. I explored which traits are core to my identity, and what differentiates me from my peers. Intended to express my identity in a way that creates emotional resonance in a memorable, yet authentic manner. Picking and choosing between different graphical themes proved challenging yet fun and helped me to understand my values and preferences as a designer even further.", imgs: ["IBD/cover1.png", "IBD/1_0.png", "IBD/1_1.png", "IBD/1_2.png", "IBD/1_3.png", "IBD/1_4.png", "IBD/1_5.png", "IBD/1_6.png"], tags: ["Graphic Design", "Illustrator"]});
project1 = Repo.insert!(%Project{class: "Personal", type: 2, name: "Portfolio Design Process", class_short: "Personal", semester: "Summer '21", desc: "Documenting the process of how I built this portfolio. Taking from what I learned from a Web Development class, I further expanded on my front-end skills by working closely with React.js, Styled Components, and FramerAnimation to deliver an engaging experience for venturing through the various works I have worked on over my college career. I went through many different design iterations, taking from tons of sites I studied found on Awwwards and Httpster. This was a fun but difficult experience trying to pinpoint a specific website style and interaction flow.", imgs: ["Website/cover.png", "Website/1_1.png", "Website/1_2.png", "Website/1_3.png", "Website/1_4.png", "Website/1_5.mp4",], tags: ["React.js", "Elixir-Phoenix", "Figma", "Experience Design"]});
project28 = Repo.insert!(%Project{class: "Personal", type: 1, name: "Collection of Song Posters", class_short: "Personal", semester: "Fall '20", desc: "A collection of a few different graphics I created for songs I've grown fond of over the years.", imgs: ["Lab/2_1.png", "Lab/2_1.png", "Lab/4_2.png", "Lab/3_1.png", "Lab/5_1.jpg", "Lab/5_2.jpg", "Lab/5_3.jpg", "Lab/5_4.jpg", "Lab/1_1.png"], tags: ["Illustrator", "Photoshop"]});
project25 = Repo.insert!(%Project{class: "Identity & Brand Design", type: 1, name: "Orchestral Era Tokens", class_short: "I&BD", semester: "Spring '21", desc: "A series of posters advertising rare, collectible tokens connected to various orchestral music eras. The center graphics of each poster/era were inspired the musical styles from each era. The Baroque era marked the beginning of light, modern structure in music compositions, the Classical era was defined by large, organized orchestral play for royalty and those in power, and the Romantic era was defined by compositions that were very emotional, expressive, and humanistic. The final set of posters were overlayed with a “Collect” tag and token shapes to further explain the product.", imgs: ["IBD/cover3.png", "IBD/3_2.png", "IBD/3_3.png", "IBD/3_4.png", "IBD/3_5.png"], tags: ["Graphic Design", "Illustrator"]});
project11 = Repo.insert!(%Project{class: "Information Design 1", type: 1, name: "NarcoCulture Infographic", class_short: "ID1", semester: "Fall '18", desc: "An infographic briefly detailing the history of Narcoculture in Mexico, highlighting the presence and distribution of various drug cartels that took over Mexico from the 1980’s to present day (2020).", imgs: ["ID1/cover1.png", "ID1/1_0.png", "ID1/1_1.png", "ID1/1_2.png", "ID1/1_3.png"], tags: ["Illustrator", "Information Design"]});
project24 = Repo.insert!(%Project{class: "Identity & Brand Design", type: 1, name: "Album Cards", class_short: "I&BD", semester: "Spring '21", desc: "A series of three marketing posters advertising an Album Trading Card Product. Inspired by the resurgence in value of pokemon trading cards, as well as the various amount of products that spotify has released over the years, I started this idea off with the intention of only targeting the hip-hop market, but expanded upon this product by designing different sets of cards, based on era and genre. I would have liked to do more “limited edition” sets of these cards, and packaging designs, but for this assignment I only explored a single set of posters.", imgs: ["IBD/cover2.png", "IBD/2_1.png", "IBD/2_2.png", "IBD/2_3.png", "IBD/2_4.png", "IBD/2_5.png", "IBD/2_6.png"], tags: ["Graphic Design", "Illustrator"]});
# project1 = Repo.insert!(%Project{class: "Personal", type: 2, name: "Yvette Kim Art", class_short: "Personal", semester: "Summer '21", desc: "", imgs: ["Website/cover.png", "Website/1_1.png", "Website/1_2.png", "Design Iteration", "Website/1_3.mp4"], tags: ["React.js", "Elixir-Phoenix", "Figma", "Experience Design"]});
# project7 = Repo.insert!(%Project{class: "Object-Oriented Design", type: 2, name: "Animator Project", class_short: "OOD", semester: "Spring '18", desc: "Final Project for Object Oriented Design", imgs: ["OOD/1_1.png]"], tags: ["Java"]});
# project8 = Repo.insert!(%Project{class: "5D Fundamentals", type: 1, name: "Fog X Flo", class_short: "5D", semester: "Fall '18", desc: "Fog X Flo project and reflection for 5D Fundamentals", imgs: ["5D/cover.png", "5D/1_1"], tags: ["Javascript", "CSS", "HTML", "Photography", "Experience Design"]});
project27 = Repo.insert!(%Project{class: "Web Development", type: 2, name: "SpotifyParty", class_short: "WebDev", semester: "Spring '21", desc: "A platform for music enthusiasts to host music parties while also receiving party feedback from guests. A SpotifyParty connects to a host's spotify account, giving them playback control, as well as the ability to manage song requests/votings from all guests of their party. Attendees (or guests), have full view of the upcoming songs in the party, as well as the standings of their votes and requests sent to the party host. For every user signed up with SpotifyParty, their party song requests, voting habits, and songs played at any party they've been to, is displayed through a series of informative graphics, as well as an Impact score based on the user’s activeness.", imgs: ["WD/cover1.png", "WD/1_2.png", "WD/1_3.png", "WD/1_1.png", "WD/1_4.png", "WD/1_5.png", "WD/1_6.png", "WD/1_7.png"], tags: ["React.js", "Elixir-Phoenix", "Web Design", "Figma"]});
project17 = Repo.insert!(%Project{class: "Typography 2", type: 1, name: "88Rising Magazine", class_short: "Type 2", semester: "Spring '19", desc: "A series of three magazine styles covering the rise in popularity around the media group: 88Rising. Featuring artists such as Rich Brain, Niki, and the Higher Brothers, I ventured into magazine/book designing for the first time in hopes of creating layouts that were engaging and reflect the energetic youth of these groups.", imgs: ["Type2/cover3.png", "Type2/3_0.jpg", "Type2/3_1.png", "Type2/3_2.jpg", "Type2/3_3.png", "Type2/3_4.png", "Type2/3_5.png", "Type2/3_6.png"], tags: ["InDesign", "Typography", "Illustrator"]});
project6 = Repo.insert!(%Project{class: "Typography 1", type: 1, name: "Type Studies", class_short: "Type 1", semester: "Spring '18", desc: "A series of typography exploration exercises from a Typography 1 course. I explored analyzing and respecting the beauty of type by pinpointing and framing the various anatomy of type in one exercise, showcased a series of typefaces of my liking in another, and created a series of logos using only letterforms in another.", imgs: ["Type1/cover2.png", "Type1/2_0.jpg", "Type1/2_1.png", "Type1/2_2.jpg", "Type1/2_3.png", "Type1/2_4.jpg", "Type1/2_5.png", "Type1/2_6.png", "Type1/2_7.jpg"], tags: ["InDesign", "Typography"]});
# project9 = Repo.insert!(%Project{class: "5D Fundamentals", type: 1, name: "CD Album Project", class_short: "5D", semester: "Fall '18", desc: "CD Album Project and reflection for 5D Fundamentals", imgs: ["5D/2_1"], tags: ["Javascript", "CSS", "HTML", "Photography", "Experience Design"]});
project10 = Repo.insert!(%Project{class: "Graphic Design 1", type: 1, name: "IFHS Film Conference", class_short: "GD1", semester: "Fall '18", desc: "Developed a series of Stamps and Posters for the International Holocaust Film Festival. Inspired by, and using pictures taken from the Holocaust Museum in downtown Boston, the posters were many to emphasize the importance of not forgetting those affected and lost by the holocaust, the stamps highlighting the countries most directly affected by the concentration camps of Hitler’s era. The stamps and logo for the poster were a result of a 100-iteration design practice.", imgs: ["GD1/cover.png", "GD1/0.png", "GD1/1.png", "GD1/2.png", "GD1/3.png", "GD1/4.png", "GD1/5.png", "GD1/6.png", "GD1/7.png"], tags: ["Illustrator", "Photography"]});

# project14 = Repo.insert!(%Project{class: "Interaction Design", type: 1, name: "CloutFit", class_short: "ID", semester: "Spring '19", desc: "CloutFit project for Interaction Design", imgs: ["ID/cover.png", "ID/1_1_.png", "ID/1_2_T.png", "ID/1_3_T.png", "ID/1_4_T.png"], tags: ["Balsamiq", "Interaction Design", "Experience Design", "Sketch"]});
# project15 = Repo.insert!(%Project{class: "Typography 2", type: 1, name: "Einstein Bagels Menu", class_short: "Type 2", semester: "Spring '19", desc: "Einstein Bagels Menu Redesign for Typography 2", imgs: ["Type2/cover1.png", "Type2/1_1_W.png", "Type2/1_2_W.png", "Type2/1_3_W.png", "Type2/1_4_W.png", "Type2/1_5_W.png"], tags: ["InDesign", "Typography", "Illustrator"]});
# project16 = Repo.insert!(%Project{class: "Typography 2", type: 1, name: "Ducktails Albums", class_short: "Type 2", semester: "Spring '19", desc: "A series 3 of CD Album Cover designs for a recent band I had just discovered. The band, Ducktails, identified with a male-vocal lead, indie-pop style. All photography in the designs were taken by me.", imgs: ["Type2/cover2.png", "Type2/2_1_W.png", "Type2/2_2_W.png", "Type2/2_3_W.png", "Type2/2_4_W.png"], tags: ["InDesign", "Typography", "Illustrator"]});
# project5 = Repo.insert!(%Project{class: "Typography 1", type: 1, name: "Siddhartha Book Design", class_short: "Type 1", semester: "Spring '18", desc: "A book design typography exercise for the first chapter of Siddhartha: an Indian Tale by Hermann Hesse. This project helped me to understand the intricacy and importance of kerning and line-height with large bodies of text in a print setting. The designing process involved printing and hand-binding (with tape) multiple sets of designs to further refine every page in this exercise.", imgs: ["Type1/cover1.png", "Type1/1_1_W.png", "Type1/1_2_T.png", "Type1/1_3_W.png"], tags: ["InDesign", "Typography"]});
# project19 = Repo.insert!(%Project{class: "Software Development", type: 2, name: "Tsuro Game", class_short: "SD", semester: "Fall '19", desc: "Final Project; Tsuro Game for Software Development", imgs: ["SD/1_1.png"], tags: ["Java"]});
# project21 = Repo.insert!(%Project{class: "Interacion Design: Mobile", type: 3, name: "UltimateGuitar App Redesign", class_short: "ID:M", semester: "Fall '20", desc: "UltimateGuitar App Redesign for Interaction Design: Mobile", imgs: ["IDM/cover2.png", "IDM/2_1_W", "IDM/2_2_W", "IDM/2_3_TM"], tags: ["Figma", "Mobile Design"]});
project22 = Repo.insert!(%Project{class: "Human Computer Interaction", type: 3, name: "NEU Covid App Redesign", class_short: "HCI", semester: "Fall '20", desc: "An app redesign of the Northeastern Covid-Tracker app, focused on simplicity and functionality. Northeastern's required forms and flows are included, such as self-screening and positive test result forms, as well as a few features such as a news tab, extended account details on a user’s profile page, and a series of articles to encourage proper and safe Covid practices.", imgs: ["HCI/cover.png", "HCI/1_1.png", "HCI/1_1_WM.mov", "HCI/1_2_WM.mov"], tags: ["Figma", "Mobile Design"]});
project12 = Repo.insert!(%Project{class: "Information Design 1", type: 1, name: "Travel Guide", class_short: "ID1", semester: "Fall '18", desc: "An infographic book illustrating the details of traveling between my home-town (Atlanta), current location (Boston), and a city that I would like to travel to (Tokyo). Details included popular venues, attractions, and various pop-culture origins. Along the bottom of the entire book runs a distance map-line, marked with popular cities that you would pass on the way to each city.", imgs: ["ID1/cover2.png", "ID1/2_3_W.png", "ID1/2_4_W.png", "ID1/2_7.png", "ID1/2_6.png", "ID1/2_5.png", "ID1/2_1_W.png", "ID1/2_2_W.png"], tags: ["Illustrator", "InDesign", "Information Design"]});

# project13 = Repo.insert!(%Project{class: "Information Design 1", type: 1, name: "How a Song is Built", class_short: "ID1", semester: "Fall '18", desc: "An infographic dissecting and explaining the anatomy of a song, in their most generic form. As complex a songs can be, I broke up what a very popular but standardized pop song from the 2000’s - 2020’s era would most likely entail, as well as the steps it takes for a song idea to develop into a produced song.", imgs: ["ID1/cover3.png", "ID1/3_1.png"], tags: ["Illustrator", "Information Design"]});



# LAB WORKS

# project28 = Repo.insert!(%Project{class: "Web Development", type: 2, name: "Events Manager", class_short: "WebDev", semester: "Spring '21", desc: "EventsApp for Web Development", imgs: ["WD/cover2.png", "WD/2_1"], tags: ["React.js", "Elixir-Phoenix"]});
# project28 = Repo.insert!(%Project{class: "Personal", type: 1, name: "Swimming Poster", class_short: "Personal", semester: "Fall '20", desc: "EventsApp for Web Development", imgs: ["Lab/4_1.png", "Lab/4_1.png"], tags: ["React.js", "Elixir-Phoenix"]});
# project29 = Repo.insert!(%Project{class: "Personal", type: 1, name: "ATL Suburbs", class_short: "Personal", semester: "Fall '20", desc: "EventsApp for Web Development", imgs: ["Film/1_1.jpeg", "Film/1_2.jpeg", "Film/1_3.jpeg", "Film/1_4.jpeg", "Film/1_5.jpeg", "Film/1_6.jpeg"], tags: ["React.js", "Elixir-Phoenix"]});
# project30 = Repo.insert!(%Project{class: "Personal", type: 1, name: "Moonstone Poster", class_short: "Personal", semester: "Fall '20", desc: "EventsApp for Web Development", imgs: ["Lab/2_1.png", "Lab/2_1.png"], tags: ["React.js", "Elixir-Phoenix"]});
# project31 = Repo.insert!(%Project{class: "Personal", type: 1, name: "OutAlee Poster", class_short: "Personal", semester: "Fall '20", desc: "EventsApp for Web Development", imgs: ["Lab/3_1.png", "Lab/3_1.png"], tags: ["React.js", "Elixir-Phoenix"]});
# project32 = Repo.insert!(%Project{class: "Personal", type: 1, name: "Blkswn Poster", class_short: "Personal", semester: "Fall '20", desc: "EventsApp for Web Development", imgs: ["Lab/1_1.png", "Lab/1_1.png"], tags: ["React.js", "Elixir-Phoenix"]});
# project33 = Repo.insert!(%Project{class: "Personal", type: 1, name: "Family Ties Poster", class_short: "Personal", semester: "Fall '20", desc: "EventsApp for Web Development", imgs: ["Lab/5_1.jpg", "Lab/5_1.jpg", "Lab/5_2.jpg", "Lab/5_3.jpg", "Lab/5_4.jpg", "Lab/5_5.png"], tags: ["React.js", "Elixir-Phoenix"]});
# project34 = Repo.insert!(%Project{class: "Personal", type: 1, name: "Tamagotchi Render", class_short: "Personal", semester: "Fall '21", desc: "For FUN", imgs: ["Lab/6_1.png", "Lab/6_1.png", "Lab/6_2.m4v", "Lab/6_3.png", "Lab/6_4.png"], tags: ["React.js", "Elixir-Phoenix"]});
# project29 = Repo.insert!(%Project{class: "Web Development", type: 1, name: "Multiplayer Tsuro Game", class_short: "WebDev", semester: "Spring '21", desc: "Multiplayer Tsuro Game for Web Development", imgs: ["WD/3_1"], tags: ["React.js", "Elixir-Phoenix"]});